services:

#kafka
  kafka:
    image: apache/kafka:3.7.0
    container_name: smartremind-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    ports:
      - "9092:9092"

    volumes:
      - kafka-data:/var/lib/kafka/data

#PostgreSQL
  postgreSQL:
    image: postgres:16
    container_name: smartremind-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root


    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

#Redis
  redis:
    image: redis:7.2
    container_name: smartremind-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data









volumes:
  kafka-data:
  pgdata:
  redis-data:
